export { useInstitutions, useInstitution, useCreateInstitution } from './useInstitutions';
export { useDepartments, useCreateDepartment, useUpdateDepartment } from './useDepartments';
export { usePrograms, useCreateProgram, useUpdateProgram } from './usePrograms';
export { useEntranceExams, useEntranceExam, useCreateEntranceExam, useLockExam, usePublishExamResults } from './useEntranceExams';
export { useRegularExams, useRegularExam, useCreateRegularExam, useUpdateExamStatus, useGenerateHallTickets, useBulkUploadResults } from './useRegularExams';
export { useApplications, useApplication, useSubmitApplication, useUpdateApplicationStatus, useShortlistApplications } from './useApplications';
export { useAttendance, useAttendanceSummary, useMarkAttendance, useBulkMarkAttendance } from './useAttendance';
export { useNotices, useCreateNotice, useUpdateNotice, useDeleteNotice } from './useNotices';
export { useDocumentRequests, useCreateDocumentRequest, useUpdateDocumentRequestStatus } from './useDocumentRequests';
export { useProctoringSessions, useProctoringStats, useReviewProctoringSession, useFlaggedEvents, useReviewFlag } from './useProctoring';

export type { Institution } from './useInstitutions';
export type { Department } from './useDepartments';
export type { Program } from './usePrograms';
export type { EntranceExam } from './useEntranceExams';
export type { RegularExam } from './useRegularExams';
export type { Application } from './useApplications';
export type { AttendanceRecord, AttendanceSummary } from './useAttendance';
export type { Notice } from './useNotices';
export type { DocumentRequest } from './useDocumentRequests';
export type { ProctoringSession, ProctoringStats } from './useProctoring';
