'use client';

import { useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Printer } from 'lucide-react';

interface HallTicketData {
  ticketNumber: string;
  studentName: string;
  enrollmentNumber: string;
  examName: string;
  examDate: string;
  examTime: string;
  duration: string;
  room: string;
  seatNumber: number;
  institutionName: string;
  institutionAddress: string;
}

interface HallTicketPDFProps {
  ticket: HallTicketData;
  showActions?: boolean;
}

export function HallTicketPDF({ ticket, showActions = true }: HallTicketPDFProps) {
  const ticketRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Hall Ticket - ${ticket.ticketNumber}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          .ticket { border: 2px solid #000; padding: 20px; max-width: 600px; margin: 0 auto; }
          .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 15px; margin-bottom: 15px; }
          .header h1 { margin: 0; font-size: 24px; }
          .header p { margin: 5px 0 0; color: #666; }
          .title { text-align: center; font-size: 18px; font-weight: bold; margin: 15px 0; text-transform: uppercase; }
          .details { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 15px 0; }
          .detail-item { padding: 8px; background: #f5f5f5; }
          .detail-label { font-size: 11px; color: #666; text-transform: uppercase; }
          .detail-value { font-size: 14px; font-weight: bold; margin-top: 2px; }
          .warning { border: 1px solid #ffc107; background: #fff3cd; padding: 10px; margin: 15px 0; font-size: 12px; }
          .footer { text-align: center; margin-top: 20px; padding-top: 15px; border-top: 1px solid #ccc; font-size: 11px; color: #666; }
          .qr-placeholder { width: 100px; height: 100px; border: 1px solid #ccc; display: flex; align-items: center; justify-content: center; margin: 10px auto; font-size: 10px; color: #999; }
        </style>
      </head>
      <body>
        <div class="ticket">
          <div class="header">
            <h1>${ticket.institutionName}</h1>
            <p>${ticket.institutionAddress}</p>
          </div>
          <div class="title">Examination Hall Ticket</div>
          <div class="qr-placeholder">QR Code</div>
          <div class="details">
            <div class="detail-item">
              <div class="detail-label">Ticket Number</div>
              <div class="detail-value">${ticket.ticketNumber}</div>
            </div>
            <div class="detail-item">
              <div class="detail-label">Student Name</div>
              <div class="detail-value">${ticket.studentName}</div>
            </div>
            <div class="detail-item">
              <div class="detail-label">Enrollment No.</div>
              <div class="detail-value">${ticket.enrollmentNumber}</div>
            </div>
            <div class="detail-item">
              <div class="detail-label">Examination</div>
              <div class="detail-value">${ticket.examName}</div>
            </div>
            <div class="detail-item">
              <div class="detail-label">Date</div>
              <div class="detail-value">${ticket.examDate}</div>
            </div>
            <div class="detail-item">
              <div class="detail-label">Time</div>
              <div class="detail-value">${ticket.examTime}</div>
            </div>
            <div class="detail-item">
              <div class="detail-label">Duration</div>
              <div class="detail-value">${ticket.duration}</div>
            </div>
            <div class="detail-item">
              <div class="detail-label">Room / Seat</div>
              <div class="detail-value">${ticket.room} / Seat ${ticket.seatNumber}</div>
            </div>
          </div>
          <div class="warning">
            <strong>Instructions:</strong> Carry this hall ticket along with a valid photo ID to the examination center.
            Arrive at least 30 minutes before the exam start time. Electronic devices are strictly prohibited.
          </div>
          <div class="footer">
            <p>This is a computer-generated document. No signature required.</p>
            <p>Generated by Uni-Edge Examination System</p>
          </div>
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  if (!showActions) {
    return (
      <div ref={ticketRef} className="border rounded-lg p-6 max-w-lg mx-auto">
        <div className="text-center border-b pb-4 mb-4">
          <h2 className="text-xl font-bold">{ticket.institutionName}</h2>
          <p className="text-sm text-muted-foreground">{ticket.institutionAddress}</p>
        </div>
        <h3 className="text-center text-lg font-semibold uppercase mb-4">Examination Hall Ticket</h3>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <div><span className="text-muted-foreground">Ticket:</span> <span className="font-mono font-bold">{ticket.ticketNumber}</span></div>
          <div><span className="text-muted-foreground">Name:</span> <span className="font-medium">{ticket.studentName}</span></div>
          <div><span className="text-muted-foreground">Enrollment:</span> <span className="font-medium">{ticket.enrollmentNumber}</span></div>
          <div><span className="text-muted-foreground">Exam:</span> <span className="font-medium">{ticket.examName}</span></div>
          <div><span className="text-muted-foreground">Date:</span> <span className="font-medium">{ticket.examDate}</span></div>
          <div><span className="text-muted-foreground">Time:</span> <span className="font-medium">{ticket.examTime}</span></div>
          <div><span className="text-muted-foreground">Room:</span> <span className="font-medium">{ticket.room}</span></div>
          <div><span className="text-muted-foreground">Seat:</span> <span className="font-medium">{ticket.seatNumber}</span></div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" onClick={handlePrint}>
        <Printer className="h-4 w-4 mr-1" />
        Print
      </Button>
      <Button variant="outline" size="sm" onClick={handlePrint}>
        <Download className="h-4 w-4 mr-1" />
        Download PDF
      </Button>
    </div>
  );
}
